#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Optional: obtain & auto-renew a Let's Encrypt TLS certificate for the
# LLM Gateway using the webroot method (zero downtime).
#
# Prerequisites:
#   * The gateway is already running and nginx serves :80 with the ACME
#     location from nginx/default.conf (location ^~ /.well-known/acme-challenge/).
#   * GATEWAY_FQDN is set in .env and resolves publicly to this host, with
#     inbound TCP/80 reachable from the internet.
#   * certbot is installed (this script installs it via dnf if missing).
#
# Usage (run as root, from the project root or anywhere):
#   sudo bash scripts/certbot-setup.sh --email you@example.org
#
# Docker (rootful) is auto-detected. For rootless Podman under a dedicated
# service account, tell the script who runs the containers so it can reload
# nginx as that user:
#   sudo CONTAINER_ENGINE=podman PODMAN_USER=nrig-service \
#        bash scripts/certbot-setup.sh --email you@example.org
#
# Use --staging first to avoid Let's Encrypt rate limits while testing.
# ---------------------------------------------------------------------------
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

EMAIL=""; STAGING=""
while [ $# -gt 0 ]; do
    case "$1" in
        --email) EMAIL="${2:-}"; shift 2 ;;
        --staging) STAGING="--staging"; shift ;;
        -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

[ -f .env ] || { echo "ERROR: .env not found in $PROJECT_DIR" >&2; exit 1; }
FQDN="$(grep -E '^GATEWAY_FQDN=' .env | head -1 | cut -d= -f2- | tr -d '"'"'"'"')"
[ -n "$FQDN" ]  || { echo "ERROR: GATEWAY_FQDN not set in .env" >&2; exit 1; }
[ -n "$EMAIL" ] || { echo "ERROR: --email is required" >&2; exit 1; }

ENGINE="${CONTAINER_ENGINE:-}"
if [ -z "$ENGINE" ]; then
    command -v docker >/dev/null 2>&1 && ENGINE=docker || ENGINE=podman
fi
PODMAN_USER="${PODMAN_USER:-}"

reload_nginx() {
    if [ -n "$PODMAN_USER" ]; then
        local uid; uid="$(id -u "$PODMAN_USER")"
        runuser -u "$PODMAN_USER" -- env XDG_RUNTIME_DIR="/run/user/$uid" \
            HOME="/home/$PODMAN_USER" PATH="/home/$PODMAN_USER/.local/bin:/usr/bin:/bin" \
            "$ENGINE" exec llm-gw-nginx nginx -s reload
    else
        "$ENGINE" exec llm-gw-nginx nginx -s reload
    fi
}

# --- ensure certbot is installed ---
if ! command -v certbot >/dev/null 2>&1; then
    echo "[certbot] installing via dnf..."
    dnf install -y epel-release >/dev/null 2>&1 || true
    dnf install -y certbot >/dev/null 2>&1 || {
        echo "ERROR: could not install certbot automatically; install it and re-run." >&2
        exit 1
    }
fi
certbot --version

install -d -m 755 "$PROJECT_DIR/certbot-webroot"

echo "[certbot] requesting cert for $FQDN (webroot: $PROJECT_DIR/certbot-webroot) $STAGING"
certbot certonly --webroot -w "$PROJECT_DIR/certbot-webroot" -d "$FQDN" \
    --email "$EMAIL" --agree-tos --non-interactive $STAGING

# --- copy certs into ssl/ (what nginx bind-mounts) ---
# docker-compose.yml bind-mounts these two files individually
# (./ssl/fullchain.pem:/etc/ssl/public.pem). A single-file bind mount is
# resolved to an inode at container start, so REPLACING the file (install/mv,
# which allocates a new inode) leaves the running container pinned to the old
# inode and 'nginx -s reload' keeps serving the stale cert. Overwrite the files
# IN PLACE (cat > file) to preserve the inode so the reload actually takes.
LIVE="/etc/letsencrypt/live/$FQDN"
cat "$LIVE/fullchain.pem" > "$PROJECT_DIR/ssl/fullchain.pem"
cat "$LIVE/privkey.pem"   > "$PROJECT_DIR/ssl/privkey.pem"
chmod 644 "$PROJECT_DIR/ssl/fullchain.pem"
chmod 600 "$PROJECT_DIR/ssl/privkey.pem"
if [ -n "$PODMAN_USER" ]; then
    chown "$PODMAN_USER:$(id -gn "$PODMAN_USER")" \
        "$PROJECT_DIR/ssl/fullchain.pem" "$PROJECT_DIR/ssl/privkey.pem"
fi

echo "[certbot] reloading nginx"
reload_nginx || echo "[certbot] WARN: nginx reload failed; restart the nginx container manually"

# --- install a renewal deploy hook so 'certbot renew' redeploys automatically ---
HOOK=/etc/letsencrypt/renewal-hooks/deploy/llm-gateway.sh
install -d -m 755 "$(dirname "$HOOK")"
cat > "$HOOK" <<HOOKEOF
#!/usr/bin/env bash
# Auto-generated by scripts/certbot-setup.sh. Runs as root from 'certbot renew'.
set -euo pipefail
PROJECT_DIR="$PROJECT_DIR"
FQDN="$FQDN"
ENGINE="$ENGINE"
PODMAN_USER="$PODMAN_USER"
LIVE="/etc/letsencrypt/live/\$FQDN"
# Overwrite in place (preserve inode) so the single-file bind mount stays valid.
cat "\$LIVE/fullchain.pem" > "\$PROJECT_DIR/ssl/fullchain.pem"
cat "\$LIVE/privkey.pem"   > "\$PROJECT_DIR/ssl/privkey.pem"
chmod 644 "\$PROJECT_DIR/ssl/fullchain.pem"
chmod 600 "\$PROJECT_DIR/ssl/privkey.pem"
if [ -n "\$PODMAN_USER" ]; then
    chown "\$PODMAN_USER:\$(id -gn "\$PODMAN_USER")" "\$PROJECT_DIR/ssl/fullchain.pem" "\$PROJECT_DIR/ssl/privkey.pem"
    uid="\$(id -u "\$PODMAN_USER")"
    runuser -u "\$PODMAN_USER" -- env XDG_RUNTIME_DIR="/run/user/\$uid" HOME="/home/\$PODMAN_USER" PATH="/home/\$PODMAN_USER/.local/bin:/usr/bin:/bin" "\$ENGINE" exec llm-gw-nginx nginx -s reload
else
    "\$ENGINE" exec llm-gw-nginx nginx -s reload
fi
HOOKEOF
chmod +x "$HOOK"

echo "[certbot] done."
echo "  cert:  $LIVE/  ->  copied to $PROJECT_DIR/ssl/{fullchain,privkey}.pem"
echo "  hook:  $HOOK (re-copies + reloads nginx on each renewal)"
echo "  timer: the certbot package's systemd timer runs 'certbot renew' automatically."
systemctl enable --now certbot-renew.timer 2>/dev/null || systemctl enable --now certbot.timer 2>/dev/null || true
systemctl list-timers 'certbot*' --no-pager 2>/dev/null | head -3 || true
